### ISSUE TITLE
Blind-Regeln ingame anzeigen

### ISSUE THREAD

**Issue by Sollunad** [Sollunad/PokerWithYourFriends#6]
* Werden schon vom Backend geliefert

**Comment by erwinru** [comment]
Ich würde nicht die ganzen Blindregeln sondern nur die aktuelle und die nächste Blindregel anzeigen. Dazu wäre noch gut wenn wir im game_state ein `current_round` einführen um anzuzeigen in welcher Runde man ist und wie viele noch bis zum nächsten Blindstep fehlen.

**Comment by Sollunad** [comment]
Done!
